version: "3.7"

volumes:
  patrones_postgres_data: {}
  patrones_postgres_data_backups: {}

services:
  postgres:
    image: postgres:14.4
    container_name: patrones_postgres
    volumes:
      - patrones_postgres_data:/var/lib/postgresql/data:Z
      - patrones_postgres_data_backups:/backups:z
    env_file:
      - .env
    ports:
      - "5432:5432"
